baseURL = 'https://omatko.pwr.edu.pl/'
relativeURLs = true
canonifyURLs = true
languageCode = 'pl-PL'
title = 'OMatKo!!!'
theme = '2026'

defaultContentLanguage = "pl"
[languages]
[languages.pl]
languageName = "Polski"

[menus]
[[menus.main]]
name = 'O konferencji'
url = '/#about'
weight = 1

[[menus.main]]
name = 'Aktualności'
pageRef = 'aktualnosci'
url = '/aktualnosci'
weight = 2


[[menus.main]]
name = 'Organizatorzy'
pageRef = 'organizatorzy'
url = '/organizatorzy'
weight = 3

[[menus.main]]
name = 'Poprzednie edycje'
pageRef = 'poprzednie-edycje'
url = 'poprzednie-edycje'
weight = 4


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[params]
# Data konferencji
conference_start = '2026-12-11T13:30'
conference_end = '2026-12-13T14:00'

# Harmonogram
show_schedule_section = true

# Rejestracja 
show_registration = true

# Linki do formularzy
participant_url = '/'
speaker_url = '/'
poster_url = '/'

# Data udostępnienia zapisów

participant_reg_open_date = '2025-10-22'
active_reg_open_date = '2025-10-02'

# Data zamkniecia zapisów

participant_reg_close_date = '2025-11-25'
active_reg_close_date = '2025-10-31'

# Zamkniecie zapisów

participant_reg_close = false
active_reg_close = false


# Sponsorzy
show_sponsors_section = true

# Patroni medialni i honorowi
show_patrons_section = true

# lokalizacja
show_map = true

# Animacja w tle
enable_background_animations = true

show_regulamin = false

math = true

enable_voting = false

vote_app_url = "https://omatko.pwr.edu.pl/glosuj/"

# aktualnosci na str glownej
show_latest_news = true