baseURL = 'https://omatko.pwr.edu.pl' 
languageCode = 'pl-PL'
title = 'OMatKo!!!' 

[menus]
  [[menus.main]]
    name = 'O konferencji'
    pageRef = '/'
    url = '/'
    weight = 1

  [[menus.main]]
    name = 'Aktualności'
    pageRef = 'aktualnosci'
    url = '/aktualnosci'
    weight = 2


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
