baseURL = 'https://omatko.pwr.edu.pl' 
languageCode = 'pl-PL'
title = 'OMatKo!!!' 

[menus]
  [[menus.main]]
    name = 'O konferencji'
    pageRef = '/'
    weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
