'on':
  push:
    branches:
      - main
    paths:
      - 'content/**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    if: "github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip build]')"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: hugo -s /home/omatko/apps/omatko

      - name: Deploy to /srv/omatko
        run: rsync -a --delete /home/omatko/apps/omatko/public/ /srv/omatko
